### ISSUE TITLE
Milestone 2 Feedback

### ISSUE THREAD

**Issue by joefsamuel** [rsk3110/risk-game#12]
- [x] Missing source code (-1). Source code not in the submitted jar file. 
- [x] Missing sequence diagram (-0.5)
- [x] When attacking, you ask how many dices are to be rolled but you don’t provide an option to enter a value.
- [x] Missing unit tests for the model (-1)
