### ISSUE TITLE
Milestone 3 Feedback

### ISSUE THREAD

**Issue by joefsamuel** [rsk3110/risk-game#19]
- [x] Missing Javadoc in submission (-1)
- [x] I don’t see your documentation folder in your submission. Missing design decisions and UML. (-1)
- [x] Your sequence diagram is missing from your submission (-0.5).
- [x] If I choose 2 players, I should be able to pick 1 of those 2 to be an AI player which is not an option.
- [x] The game keeps getting stuck at the ‘Configure Your Game’ pane. (-2)
    - [x] Your game keeps getting stuck when I choose 3 players and 2 AI Players or any such combination where I have an AI.
    - [x] It is stuck even if I choose no AI players with any number of players.
    - [x] I was unable to play the game.
